### ISSUE TITLE
Listing Lambdeth as an EVM Package

### ISSUE THREAD

**Issue by rrecuero** [siromivel/lambdeth#1]
Levi, Tara, it was great meeting you at EThDenver.  Hope you got some well-deserved rest.

We believe Lambdeth could be a great EVM package for the ecosystem once is finished.
Once the code is complete and deployed to mainnet, we could list it on our repository so the community can use it. You have more info about the process here ([Create an EVM Package](https://blog.zeppelinos.org/evm-package-deployment-with-zeppelinos-part-i-introduction-and-creating-a-linkedlist-contract/))

Here is the registry: https://registry.zeppelinos.org/

If you have any questions, please feel free to reach out at ramon@zeppelin.solutions

**Comment by siromivel** [comment]
I think our plan from here is to implement a few more utility methods(I just added a bunch of issues for those,) and then get this pushed to mainnet/register with ZOS. There's plenty more methods that would be nice to expose but they'll be a fun test of the upgradeable package system!

**Comment by siromivel** [comment]
@rrecuero This should be live on ZOS now, the initial deployment was fairly easy and I've successfully updated it a few times now as well without issue.

npm package can be found here: https://www.npmjs.com/package/lambdeth
